services:
  postgres:
    container_name: postgres
    build:
      context: ./postgres
      dockerfile: Dockerfile
    # command: -c idle_session_timeout=60000 # Set 1 min timeout on idle connection 
    env_file:
      - public.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p 5432"]
      interval: 5s
      timeout: 5s
      retries: 3

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped  # Ensure the server restarts on crash
    env_file:
      - public.env
      - private.env
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    volumes:
      - ./server/templates:/app/templates
      - ./server/static:/app/static
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data: