# Logging
DEFAULT_LOG_LEVEL = "INFO"

# Postgres
## Connections settings
DEFAULT_POSTGRES_HOST = "postgres"
DEFAULT_POSTGRES_PORT = 5432
DEFAULT_POSTGRES_DB = "postgres"
DEFAULT_POSTGRES_USER = "postgres"
DEFAULT_POSTGRES_PASSWORD = "postgres"
## Connection pool
DEFAULT_POOL_MINCONN = 2
DEFAULT_POOL_MAXCONN = 20
DEFAULT_POOL_CONN_RETRIES = 5
DEFAULT_POOL_CONN_RETRY_DELAY = 10

# FastAPI application
DEFAULT_DEV_PORT = 80
DEFAULT_DEV_HOST = "server"
DEFAULT_DEV_PROTOCOL = "http"
## Filenames
DEFAULT_FILENAME_REPORT_CSV = "report.csv"
DEFAULT_FILENAME_DATASET_CSV = "dataset.csv"

# Questions
QUESTION_MULTICHOICE_TYPES = ("multichoice", "multichoiceset")
QUESTION_CODERUNNER_TYPES = ("coderunner",)
QUESTION_CLOZE_TYPES = ("cloze",)
KNOWN_QUESTION_TYPES = (
    QUESTION_MULTICHOICE_TYPES + QUESTION_CODERUNNER_TYPES + QUESTION_CLOZE_TYPES
)

# Frontend
DEFAULT_FRONTEND_LANGUAGE = "ru"

# Redis Session Storage
DEFAULT_REDIS_HOST = "redis"
DEFAULT_REDIS_PORT = 6379
DEFAULT_REDIS_PASSWORD = "my_redis_password"
DEFAULT_REDIS_USER = "my_user"
DEFAULT_REDIS_USER_PASSWORD = "my_user_password"
DEFAULT_REDIS_POOL_SIZE = 20
DEFAULT_REDIS_DB = 0
DEFAULT_REDIS_EX = 900  # 15 min
