# Logging
DEFAULT_LOG_LEVEL="INFO"

# Postgres
## Connection pool
DEFAULT_POOL_CONN_RETRIES=5
DEFAULT_POOL_CONN_RETRY_DELAY=10

# FastAPI application
DEFAULT_DEV_PORT="8080"

# Questions
QUESTION_MULTICHOICE_TYPES = ("multichoice", "multichoiceset")
QUESTION_CODERUNNER_TYPES = ("coderunner",)
QUESTION_CLOZE_TYPES = ('cloze',)
KNOWN_QUESTION_TYPES = QUESTION_MULTICHOICE_TYPES + QUESTION_CODERUNNER_TYPES + QUESTION_CLOZE_TYPES